kubelet:
  enabled: true
  namespace: kube-system
  serviceMonitor:
    additionalLabels:
      monitoring-by: prometheus

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true

prometheus:
  enabled: true

  prometheusSpec:

    global:
      scrape_interval: 5s
      scrape_timeout: 4s

    serviceMonitorSelectorNilUsesHelmValues: true

    scrapeConfigSelectorNilUsesHelmValues: false
    additionalScrapeConfigs: []

    additionalScrapeConfigsInternal:
      - job_name: "external-node-exporters"
        static_configs:
          - targets:
              - "192.168.0.101:9100"
              - "192.168.0.102:9100"
              - "192.168.0.103:9100"

    storageSpec: null

    retention: 2h

    resources:
      requests:
        cpu: 200m
        memory: 1Gi