apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s
      scrape_timeout: 4s

    scrape_configs:

      - job_name: "prometheus"
        static_configs:
        - targets: ["localhost:9090"]

      - job_name: "node-exporters"
        static_configs:
        - targets:
          - "192.168.0.101:9100"
          - "192.168.0.102:9100"
          - "192.168.0.103:9100"

      - job_name: "kube-state-metrics"
        static_configs:
        - targets:
          - "kube-state-metrics.monitoring.svc.cluster.local:8080"

      - job_name: "kubelet"
        metrics_path: /metrics
        scheme: https
        tls_config:
          insecure_skip_verify: true
        static_configs:
        - targets:
          - "192.168.0.101:10250"
          - "192.168.0.102:10250"
          - "192.168.0.103:10250"

      - job_name: "cadvisor"
        metrics_path: /metrics/cadvisor
        scheme: https
        tls_config:
          insecure_skip_verify: true
        static_configs:
        - targets:
          - "192.168.0.101:10250"
          - "192.168.0.102:10250"
          - "192.168.0.103:10250"